#!/bin/bash
webstr=$(wget -qO- --no-check-certificate "$1")
alm3u8=$(echo $webstr|sed 's/.*hlsManifestUrl":\(.*\)}.*/\1/g'|cut -d} -f1|cut -d, -f1|sed 's/\"//g')
m3u8=$(wget -qO- --no-check-certificate "$alm3u8"|tail -n 1)
echo $m3u8
